### ISSUE TITLE
cannot access any other controller route

### ISSUE THREAD

**Issue by danieldmo** [markmur/sails-react-webpack#1]
if you do something like this 

```
'GET /': {
    controller: 'AppController',
    action: 'index',
    skipAssets: true,
  },

  'GET /test': { controller: 'AppController', action: 'test', skipAssets: true },
```

instead of 

```
'GET /*': {
    controller: 'AppController',
    action: 'index',
    skipAssets: true,
  },
```

we can use the controllers for api calls as well rendering pages

**Comment by danieldmo** [comment]
but then all routes defined in react-router will have to be sent through the sails router as well, which is another problem

**Comment by danieldmo** [comment]
the solution I found was to replace `api/responses/notFound.js`

```
// api/responses/notFound.js
module.exports = function notFound (data, options) {

  var bundle;

  if (sails.config.environment === 'production') {
    bundle = require('../../assets.json').main.js;
    console.log(bundle);
  }

  return this.res.view('index', {
    bundle: bundle,
  });
});
```

so if we don't have a route for controller we are trying to reach it redirects to the default `/`

**Comment by markmur** [comment]
So what sails allows is controller prefixing. If react is responsible for all rendering, then the controller routes can be prefixed with '/api' or something similar. This can either be specific to each controller or can be added globally in `config/blueprints.js`

This is for an SPA though obviously, not a multi-page app where we serve the templates.

All routes other than '/api' serve the react app.

**Comment by danieldmo** [comment]
I want to use the sails-hook-user, how would you go about it ?

with my solution above, I can use it normally now

**Comment by markmur** [comment]
Are those routes defined _before_ the `config/routes.js` ones?

**Comment by markmur** [comment]
If so it should just work straight out of the box without using react at all. I can't say without testing it though

**Comment by danieldmo** [comment]
you should add a comment in the sails routes and close this issue

**Comment by markmur** [comment]
Will do. I might migrate this repo to the Boxfish org
