### ISSUE TITLE
Sails sockets fail to inititialize

### ISSUE THREAD

**Issue by ckee83** [markmur/sails-react-webpack#2]
Having an easy time with the scaffolding so far with one exception. The sails.io.js dependency is failing to load making websockets unavailable.

I was able to easily reproduce this from source code with the following:
1. `git clone ...`
2. `cd sails-react-webpack`
3. `npm install`
4. `nf start`
5. open browser and navigate to localhost:3000
6. open dev-tools/console
7. observe that sails.io.js has not been loaded and the iconic sail boat message is missing

Please let me know if there's anything I can do to help resolve this.

**Comment by markmur** [comment]
Hey @ckee83, you can move the sails.io.js file from `/assets` to `/public` and then import it in your `views/layout.ejs` file with a simple script tag.

```
<script src="/sails.io.js"></script>
```

This will auto-connect to sails and you'll notice `io.sails` will be available in the dev console.
