### ISSUE TITLE
Fails build and run

### ISSUE THREAD

**Issue by joncodo** [markmur/sails-react-webpack#4]
<img width="710" alt="screen shot 2017-01-02 at 8 36 04 pm" src="https://cloud.githubusercontent.com/assets/3011407/21598040/1ffdab20-d12b-11e6-88ee-3cb07841595d.png">

after npm i:

<img width="504" alt="screen shot 2017-01-02 at 8 36 39 pm" src="https://cloud.githubusercontent.com/assets/3011407/21598041/2dcf2602-d12b-11e6-8b07-f2b2e89a0904.png">

**Comment by joncodo** [comment]
npm i babel-core --save fixes this but there is no css. Is that intended?

**Comment by markmur** [comment]
Hey @joncodo, thanks for pointing out the babel-core install error. I'll make sure to add this to the package.

As for the CSS, it should be loading a very minimal amount of css from the `app.scss` in `/assets/styles/`

**Comment by joncodo** [comment]
You are right. The css is there

**Comment by markmur** [comment]
I've added `babel-core` and published a patch on NPM so I'm going to close this. Feel free to open additional issues if you find any other problems 👍

**Comment by joncodo** [comment]
Awesome. Nice project :)
