### ISSUE TITLE
cannot create with node v7

### ISSUE THREAD

**Issue by ghost** [markmur/sails-react-webpack#6]
The package is using node 5.8.0 and I am using node 7.x.x
Why using node 5.8 and not node higher the 5.8?

**Comment by markmur** [comment]
Thanks for reporting @elihayun1. Pull requests are welcome! :) I'm busy as ever these days so it might take some time for me to get around to it.

**Comment by markmur** [comment]
@elihayun1 is it throwing some sort of error? Works for me with Node v7.7.1

**Comment by markmur** [comment]
Node engines updated via #7
